[package]
name = "ember"
version = "1.0.0"
authors = []

[addresses]
ember = "0xb0179ef93bc9d50fdf656fe60846202e074cb181dc13a2d61554161ffc4988bb"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.18"
subdir = "aptos-move/framework/aptos-framework"
