[package]
name = "ember"
version = "1.0.0"
authors = []

[addresses]
ember = "0x1addd32869cedb5edef94f3ab1e1db481c16fb82baea80130c5683b53d4aee98"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.18"
subdir = "aptos-move/framework/aptos-framework"
